// <auto-generated />
using Lantor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lantor.Data.Migrations
{
    [DbContext(typeof(LantorContext))]
    partial class LantorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lantor.DomainModel.Alphabet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alphabets");
                });

            modelBuilder.Entity("Lantor.DomainModel.LanguageSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MultilingualSampleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MultilingualSampleId");

                    b.ToTable("LanguageSamples");
                });

            modelBuilder.Entity("Lantor.DomainModel.LanguageVectorCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlphabetId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageSampleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlphabetId");

                    b.HasIndex("LanguageSampleId");

                    b.ToTable("LanguageVectorCache");
                });

            modelBuilder.Entity("Lantor.DomainModel.MultilingualSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MultilingualSamples");
                });

            modelBuilder.Entity("Lantor.DomainModel.Alphabet", b =>
                {
                    b.OwnsMany("Lantor.DomainModel.LetterVector", "LetterVectors", b1 =>
                        {
                            b1.Property<int>("AlphabetId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<char>("Letter")
                                .HasColumnType("character(1)");

                            b1.HasKey("AlphabetId", "Id");

                            b1.ToTable("LetterVector");

                            b1.WithOwner()
                                .HasForeignKey("AlphabetId");

                            b1.OwnsOne("Lantor.DomainModel.HiDimBipolarVector", "Vector", b2 =>
                                {
                                    b2.Property<int>("LetterVectorAlphabetId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("LetterVectorId")
                                        .HasColumnType("integer");

                                    b2.Property<byte[]>("Data")
                                        .IsRequired()
                                        .HasColumnType("bytea");

                                    b2.HasKey("LetterVectorAlphabetId", "LetterVectorId");

                                    b2.ToTable("LetterVector");

                                    b2.WithOwner()
                                        .HasForeignKey("LetterVectorAlphabetId", "LetterVectorId");
                                });

                            b1.Navigation("Vector")
                                .IsRequired();
                        });

                    b.Navigation("LetterVectors");
                });

            modelBuilder.Entity("Lantor.DomainModel.LanguageSample", b =>
                {
                    b.HasOne("Lantor.DomainModel.MultilingualSample", null)
                        .WithMany("Languages")
                        .HasForeignKey("MultilingualSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lantor.DomainModel.LanguageVectorCache", b =>
                {
                    b.HasOne("Lantor.DomainModel.Alphabet", "Alphabet")
                        .WithMany()
                        .HasForeignKey("AlphabetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lantor.DomainModel.LanguageSample", "LanguageSample")
                        .WithMany()
                        .HasForeignKey("LanguageSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lantor.DomainModel.HiDimBipolarVector", "Vector", b1 =>
                        {
                            b1.Property<int>("LanguageVectorCacheId")
                                .HasColumnType("integer");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.HasKey("LanguageVectorCacheId");

                            b1.ToTable("LanguageVectorCache");

                            b1.WithOwner()
                                .HasForeignKey("LanguageVectorCacheId");
                        });

                    b.Navigation("Alphabet");

                    b.Navigation("LanguageSample");

                    b.Navigation("Vector")
                        .IsRequired();
                });

            modelBuilder.Entity("Lantor.DomainModel.MultilingualSample", b =>
                {
                    b.Navigation("Languages");
                });
#pragma warning restore 612, 618
        }
    }
}
